version: '3.8'

services:
  hr-manager:
    build:
      context: .
      dockerfile: ./HrManager/Dockerfile
    deploy:
      replicas: 1
    environment:
      PREFS_AMOUNT: 10
    ports:
      - "${HR_MANAGER_PORT}:8080"
    networks:
      - hackathon_net

  hr-director:
    build:
      context: .
      dockerfile: ./HrDirector/Dockerfile
    deploy:
      replicas: 1
    ports:
      - "${HR_DIRECTOR_PORT}:8080"
    networks:
      - hackathon_net

  teamlead-1:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 6
    ports:
      - "${TEAMLEAD_1_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net

  teamlead-2:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 7
    ports:
      - "${TEAMLEAD_2_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net

  teamlead-3:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 8
    ports:
      - "${TEAMLEAD_3_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net
  
  teamlead-4:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 9
    ports:
      - "${TEAMLEAD_4_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net
  
  teamlead-5:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 10
    ports:
      - "${TEAMLEAD_5_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net
  
  junior-1:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 1
    ports:
      - "${JUNIOR_1_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net
  
  junior-2:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 2
    ports:
      - "${JUNIOR_2_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net
  
  junior-3:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 3
    ports:
      - "${JUNIOR_3_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net

  junior-4:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 4
    ports:
      - "${JUNIOR_4_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net
  
  junior-5:
    image: developer:latest
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 5
    ports:
      - "${JUNIOR_5_PORT}:8080"
    depends_on:
      - hr-director
      - hr-manager
    networks:
      - hackathon_net

networks:
  hackathon_net:
    driver: bridge
