version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon_net

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d hackathon-problem -U postgres || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hackathon_net
  
  hr-manager:
    build:
      context: .
      dockerfile: ./HrManager/Dockerfile
    deploy:
      replicas: 1
    environment:
      PREFS_AMOUNT: ${PREFS_AMOUNT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${HR_MANAGER_PORT}:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      teamlead-1:
        condition: service_started
      teamlead-2:
        condition: service_started
      teamlead-3:
        condition: service_started
      teamlead-4:
        condition: service_started
      teamlead-5:
        condition: service_started
      junior-1:
        condition: service_started
      junior-2:
        condition: service_started
      junior-3:
        condition: service_started
      junior-4:
        condition: service_started
      junior-5:
        condition: service_started
    networks:
      - hackathon_net

  hr-director:
    build:
      context: .
      dockerfile: ./HrDirector/Dockerfile
    deploy:
      replicas: 1
    environment:
      PREFS_AMOUNT: ${PREFS_AMOUNT}
      CONNECTION_STRING: "Host=db;Port=5432;Database=hackathon-problem;Username=postgres;Password=postgres"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      HACKATHON_EVENT_TIMES: ${HACKATHON_EVENT_TIMES}
    ports:
      - "${HR_DIRECTOR_PORT}:8080"
    networks:
      - hackathon_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      hr-manager:
        condition: service_started
  
  teamlead-1:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 6
      QUEUE_NAME: ${QUEUE_NAME_TEAMLEAD_1}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${TEAMLEAD_1_PORT}:8080"

  teamlead-2:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 7
      QUEUE_NAME: ${QUEUE_NAME_TEAMLEAD_2}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${TEAMLEAD_2_PORT}:8080"

  teamlead-3:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 8
      QUEUE_NAME: ${QUEUE_NAME_TEAMLEAD_3}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${TEAMLEAD_3_PORT}:8080"

  teamlead-4:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 9
      QUEUE_NAME: ${QUEUE_NAME_TEAMLEAD_4}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${TEAMLEAD_4_PORT}:8080"

  teamlead-5:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: teamlead
      ID: 10
      QUEUE_NAME: ${QUEUE_NAME_TEAMLEAD_5}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${TEAMLEAD_5_PORT}:8080"

  junior-1:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 1
      QUEUE_NAME: ${QUEUE_NAME_JUNIOR_1}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${JUNIOR_1_PORT}:8080"

  junior-2:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 2
      QUEUE_NAME: ${QUEUE_NAME_JUNIOR_2}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${JUNIOR_2_PORT}:8080"

  junior-3:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 3
      QUEUE_NAME: ${QUEUE_NAME_JUNIOR_3}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${JUNIOR_3_PORT}:8080"

  junior-4:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 4
      QUEUE_NAME: ${QUEUE_NAME_JUNIOR_4}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${JUNIOR_4_PORT}:8080"

  junior-5:
    build:
      context: .
      dockerfile: ./Developer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hackathon_net
    deploy:
      replicas: 1
    environment:
      TYPE: junior
      ID: 5
      QUEUE_NAME: ${QUEUE_NAME_JUNIOR_5}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "${JUNIOR_5_PORT}:8080"

networks:
  hackathon_net:
    driver: bridge
