<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <StartupObject>HrDirector.HrDirectorMainProgram</StartupObject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Common/Common.csproj"/>
    </ItemGroup>

</Project>